# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEndToEndTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_endToEndTest(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(1552, 936)
    self.driver.find_element(By.NAME, "item").click()
    self.driver.find_element(By.NAME, "item").send_keys("test1")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.NAME, "item").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".container > form > button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "item").send_keys("test2")
    self.driver.find_element(By.CSS_SELECTOR, ".container > form > button").click()
    self.driver.find_element(By.NAME, "new_item").click()
    self.driver.find_element(By.NAME, "new_item").send_keys("rename test1")
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) button").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
  
