name: Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-flask-app .

    - name: Run Unit Tests
      run: docker run my-flask-app python unit-test.py

    - name: Run Integration Tests
      run: docker run my-flask-app python -m unittest endToEnd-test.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Image to Docker Hub
      run: |
        docker tag my-flask-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest