name: Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-flask-app .

    - name: start docker
      run: docker run -d -p 5000:5000 my-flask-app
    
    - name: Run unit tests
      run: python -m unittest discover unit-test

    - name: Run integration tests
      run: python -m unittest discover integration-test

    - name: Stop docker
      run: docker stop $(docker ps -q --filter ancestor=my-flask-app )

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Image to Docker Hub
      run: |
        docker tag my-flask-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest