name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: start docker
        run: docker run -d -p 5000:5000 flask-app

      - name: Running unit tests
        run: python -m unittest discover unit_tests

      - name: Running integration tests
        run: python -m unittest discover integration_test

      - name: Stop docker
        run: docker stop $(docker ps -q --filter ancestor=flask-app )

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Push Image to Docker Hub
        run: |
          docker tag flask-app ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest